### ISSUE TITLE
Name labels no longer rendered

### ISSUE THREAD

**Issue by wolfy1339** [hiddewie/OpenRailwayMap-vector#92] opened 2024-08-04 20:23 UTC
I am not sure if this is known, but the name labels for tracks are no longer being rendered.

Currenly running revision dc4f5b9960471587157f5c0384c49c3ff52fe5f7 and there are no labels for tracks anymore

**Comment by hiddewie** [comment] 2024-08-05 07:52
I cannot reproduce this locally or in the deployed variant on https://openrailwaymap.fly.dev/#view=11.42/51.0568/3.8426&style=standard  

![image](https://github.com/user-attachments/assets/47f6f4a0-3af5-4e31-a743-def126bb6efa)

Did you try to reimport the data and rebuild/restart the proxy? The past days quite some breaking changes were made to the database schema, layers and the rendering properties.

**Comment by hiddewie** [comment] 2024-08-05 07:54
Track refs also still render correctly for me 

![image](https://github.com/user-attachments/assets/9c345689-a525-42e1-8c99-a226697b9b9a)

**Comment by wolfy1339** [comment] 2024-08-05 15:13
Yes, I have run a re-import of the db.

Track refs do render, just not the `name=*` tag
What you are showing is the `ref=*` tag and the `railway:track_ref=*` tags, but not the `name=*` tag

**Comment by wolfy1339** [comment] 2024-08-12 17:37
The name is present in the database
```
gis=# select name from railway_line where osm_id=102000741;
            name            
----------------------------
 Trois-Rivières Subdivision
(1 row)
```

**Comment by hiddewie** [comment] 2024-09-01 12:03
Thanks, I managed to reproduce it.

Should be fixed after https://github.com/hiddewie/OpenRailwayMap-vector/commit/03e86878e1179031f9c278a959564c282993390c

![image](https://github.com/user-attachments/assets/37b6af5f-3f19-4204-8eb2-f2564832acdd)

![image](https://github.com/user-attachments/assets/fad8b672-2148-42f7-9185-d66c0e3d6218)

**Closed** 2024-09-01 12:03 UTC
